### ISSUE TITLE
Persistence Manager validation

### ISSUE THREAD

**Issue by simonelbaz** [woonsan/jackrabbit-datastore-migration#2]
Hi woonsan,

Is there a way to check a JCR PersistentData Manager with your datastore migration tool ?

Thanks for any advice
Simon

**Comment by woonsan** [comment]
Hi Simon,

This project narrows its scope only for `DataStore`.
Apache Jackrabbit Standalone [1] has many features, such as backup, using PersistenceManager.
Hippo CMS Repository, using Apache Jackrabbit as its core, has a checker tool using PersistenceManager, too. [2,3] Those three could be interesting to you.

Regards,

Woonsan

[1] http://jackrabbit.apache.org/jcr/standalone-server.html
[2] https://www.onehippo.org/library/administration/maintenance/checker-tool.html
[3] https://code.onehippo.org/cms-community/hippo-addon-checker/tree/hippo-addon-checker-2.1.0

**Comment by simonelbaz** [comment]
Thanks a lot for your answer
